### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by Yanyi-Zhang** [ExplainableML/KG-SP#3]
Hello, I encountered some issues when reproducing the code you provided. Could you please advise on how to solve them?
Traceback (most recent call last):
  File "train.py", line 348, in <module>
    main()
  File "train.py", line 43, in main
    trainset = dset.CompositionDataset(
  File "/sharefiles1/zhangyanyi/projects/kg-sp/data/dataset.py", line 168, in __init__
    sample_mask = pickle.load(fo)
  File "/home/zhangyanyi/miniconda3/envs/czsl-1/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by sgk98** [comment]
Hello,
Apologies for the late reply. Lines 164,168 and 170 in `data/dataset.py` needed to be modified to load the files with the correct setting (`rb`). I have made the required fix now.
I hope this helps.
